insert into Generation
values
((select uuid()), 'kanto', 'Kanto'),
((select uuid()), 'johto', 'Johto'),
((select uuid()), 'hoenn', 'Hoenn'),
((select uuid()), 'sinnoh', 'Sinnoh'),
((select uuid()), 'unova', 'Unova'),
((select uuid()), 'kalos', 'Kalos'),
((select uuid()), 'alola', 'Alola'),
((select uuid()), 'galar', 'Galar');

insert into Location
values
((select uuid()),'albania','Albania'),
((select uuid()),'andorra','Andorra'),
((select uuid()),'armenia', 'Armenia'),
((select uuid()),'austria', 'Austria'),
((select uuid()),'azerbaijan', 'Azerbaijan'),
((select uuid()),'belarus', 'Belarus'),
((select uuid()),'belgium', 'Belgium'),
((select uuid()),'bosnia-and-herzegovina', 'Bosnia And Herzegovina'),
((select uuid()),'bulgaria','Bulgaria'),
((select uuid()),'croatia', 'Croatia'),
((select uuid()),'cyprus', 'Cyprus'),
((select uuid()),'czech-republic', 'Czech Republic'),
((select uuid()),'denmark', 'Denamrk'),
((select uuid()),'estonia', 'Estonia'),
((select uuid()),'finland', 'Finland'),
((select uuid()),'france', 'France'),
((select uuid()),'georgia', 'Georgia'),
((select uuid()),'germany', 'Germany'),
((select uuid()),'greece', 'Greece'),
((select uuid()),'hungary', 'Hungary'),
((select uuid()),'iceland', 'Iceland'),
((select uuid()),'ireland',  'Ireland'),
((select uuid()),'italy',  'Italy'),
((select uuid()),'kazakhstan', 'Kazakhstan'),
((select uuid()),'latvia', 'Latvia'),
((select uuid()),'liechtenstein', 'Liechtenstein'),
((select uuid()),'lithuania', 'Lithuania'),
((select uuid()),'luxembourg', 'Luxembourg'),
((select uuid()),'macedonia', 'Macedonia'),
((select uuid()),'malta', 'Malta'),
((select uuid()),'moldova', 'Moldavia'),
((select uuid()),'monaco', 'Monaco'),
((select uuid()),'montenegro', 'Montenegro'),
((select uuid()),'netherlands', 'Netherlands'),
((select uuid()),'norway', 'Norway'),
((select uuid()),'poland', 'Poland'),
((select uuid()),'portugal', 'Portugal'),
((select uuid()),'romania', 'Romania'),
((select uuid()),'russia', 'Russia'),
((select uuid()),'san-marino', 'San Marino'),
((select uuid()),'serbia', 'Serbia'),
((select uuid()),'slovakia', 'Slovakia'),
((select uuid()),'slovenia', 'Slovenia'),
((select uuid()),'spain', 'Spain'),
((select uuid()),'sweden', 'Swedeen'),
((select uuid()),'switzerland', 'Switzerland'),
((select uuid()),'turkey', 'Turkey'),
((select uuid()),'ukraine', 'Ukraine'),
((select uuid()),'united-kingdom', 'United-kingdom'),
((select uuid()),'vatican-city', 'Vatican-city');

insert into Type
values
((select uuid()),'bug', 'Bug'),
((select uuid()), 'dark', 'Dark'),
((select uuid()), 'dragon', 'Dragon'),
((select uuid()), 'electric', 'Electric'),
((select uuid()), 'fairy', 'Fariry'),
((select uuid()), 'fighting', 'Fighting'),
((select uuid()), 'fire', 'Fire'),
((select uuid()), 'flying', 'Flying'),
((select uuid()), 'ghost', 'Ghost'),
((select uuid()), 'grass', 'Grass'),
((select uuid()), 'ground', 'Ground'),
((select uuid()), 'ice', 'Ice'),
((select uuid()), 'normal', 'Normal'),
((select uuid()), 'poison', 'Poisnon'),
((select uuid()), 'psychic', 'Psychic'),
((select uuid()), 'rock', 'Rock'),
((select uuid()), 'steel', 'Steel'),
((select uuid()), 'water', 'Water');

insert into User
values
((select uuid()), 'DiskoSjenka'),
((select uuid()), 'rhaenys0173');